### ISSUE TITLE
Run NASA Environment federate locally so we can test locally.

### ISSUE THREAD

**Issue by Washingtonwei** [blueberryboson/mwsu_sim2017#12]
You can download the SEE 2017 Environment Federate from:
SEE Assembla repository (2017 folder);
Google Drive at: https://drive.google.com/drive/folders/0B5VINCL02C8rdG1MVHUzYTFPZDA?usp=sharing;

**Comment by MounceCL** [comment]
I don't think we need to download the Environment federate ourselves to test anymore. Mike Conroy said they were going to leave it running on the Federation all the time.

**Comment by Washingtonwei** [comment]
Great, then I will close this issue.
